import {
    activearea_api,
    activebuildbase_api,
    activebuildtype_api,
    activelandstatus_api,
    activemainproject_api,
    activepurpose_api,
    activesubproject_api,
    activeusageland_api,
    areaname_api,
    buildbase_api,
    buildtype_api,
    creatarea_api,
    creatbuildbase_api,
    creatbuildtype_api,
    creatlandstatus_api,
    creatmainproject_api,
    creatpurpose_api,
    creatsubproject_api,
    creatusageland_api,
    deactivearea_api,
    deactivebuildbase_api,
    deactivebuildtype_api,
    deactivelandstatus_api,
    deactivemainproject_api,
    deactivepurpose_api,
    deactivesubproject_api,
    deactiveusageland_api,
    deletearea_api,
    deletebuildbase_api,
    deletebuildtype_api,
    deletelandstatus_api,
    deletemainproject_api,
    deletepurpose_api,
    deletesubproject_api,
    deleteusageland_api,
    landstatus_api,
    mainproject_api,
    purpose_api,
    subproject_api,
    systemform_api,
    updatearea_api,
    updatebuildbase_api,
    updatebuildtype_api,
    updatelandstatus_api,
    updatemainproject_api,
    updatepurpose_api,
    updatesubproject_api,
    updateusageland_api,
    usageland_api
} from './DXBConstant';

export const MasterModelConfig = {
    areaname: {
        mastertitle: 'areaname',
        addformtitle: 'addareaname',
        editformtitle: 'editareaname',
        formRoute: 'areaname',
        titleField: 'englishname',
        displayFields: ['areacode', 'englishname', 'arabicname', 'status'],
        displayLabels: {
            areacode: 'code',
            englishname: 'englishname',
            arabicname: 'arabicname' ,
            status: 'status',
        },
        formFields: [
            { name: 'areacode', label: 'areacode', type: 'text' },
            { name: 'englishname', label: 'englishname', type: 'text' },
            { name: 'arabicname', label: 'arabicname', type: 'text' },
            { name: 'status', label: 'status', type: 'picker', options: [{ label: 'active', value: 1 }, { label: 'inactive', value: 0 }] },
        ],
        api: {
            list: areaname_api,
            delete: deletearea_api,
            activate: activearea_api,
            deactivate: deactivearea_api,
            create: creatarea_api,
            update: updatearea_api,
        },
    },
    purpose: {
        mastertitle: 'purpose',
        addformtitle: 'addpurpose',
        editformtitle: 'arabicname',
        formRoute: 'purpose',
        titleField: 'englishname',
        displayFields: ['englishname', 'arabicname', 'status'],
        displayLabels: {
            englishname: 'englishname',
            arabicname: 'arabicname',
            status: 'status',
        },
        formFields: [
            { name: 'englishname', label: 'englishname', type: 'text' },
            { name: 'arabicname', label: 'arabicname', type: 'text' },
            { name: 'status'    , label: 'status', type: 'picker', options: [{ label: 'active', value: 1 }, { label: 'inactive', value: 0 }] },
        ],
        api: {
            list: purpose_api,
            delete: deletepurpose_api,
            activate: activepurpose_api,
            deactivate: deactivepurpose_api,
            create: creatpurpose_api,
            update: updatepurpose_api,
        },
    },
    buildtype: {
        mastertitle: 'buildtype',
        addformtitle: 'addbuildtype',
        editformtitle: 'editbuildtype',
        formRoute: 'buildtype',
        displayFields: ['englishname', 'arabicname', 'status'],
        titleField: 'englishname',
        displayLabels: {
            englishname: 'englishname',
            arabicname: 'arabicname',
            status: 'status',
        },
        formFields: [
            { name: 'englishname', label: 'englishname', type: 'text' },
            { name: 'arabicname' , label: 'arabicname', type: 'text' },
            { name: 'status'     , label: 'status', type: 'picker', options: [{ label: 'active', value: 1 }, { label: 'inactive', value: 0 }] },
        ],
        api: {
            list: buildtype_api,
            delete: deletebuildtype_api,
            activate: activebuildtype_api,
            deactivate: deactivebuildtype_api,
            create: creatbuildtype_api,
            update: updatebuildtype_api,
        },
    },
    usageevaluation: {
        mastertitle: 'usageevaluation',
        addformtitle: 'addusage',
        editformtitle: 'editusage',
        formRoute: 'usageevaluation',
        titleField: 'englishname',
        displayFields: ['englishname', 'arabicname', 'status'],
        displayLabels: {
            englishname: 'englishname',
            arabicname: 'arabicname',
            status: 'status',
        },
        formFields: [
            { name: 'englishname', label: 'englishname', type: 'text' },
            { name: 'arabicname', label: 'arabicname', type: 'text' },
            { name: 'status', label: 'status', type: 'picker', options: [{ label: 'active', value: 1 }, { label: 'inactive', value: 0 }] },
        ],
        api: {
            list: usageland_api,
            delete: deleteusageland_api,
            activate: activeusageland_api,
            deactivate: deactiveusageland_api,
            create: creatusageland_api,
            update: updateusageland_api,
        },
    },
    unitmainproject: {
        mastertitle: 'mainprojectname',
        addformtitle: 'addmainproject',
        editformtitle: 'editmainproject',
        formRoute: 'unitmainproject',
        displayFields: ['englishname', 'arabicname', 'status'],
        titleField: 'englishname',
        displayLabels: {
            englishname: 'englishname',
            arabicname: 'arabicname',
            status: 'status',
        },
        formFields: [
            { name: 'englishname', label: 'englishname', type: 'text' },
            { name: 'arabicname', label: 'arabicname', type: 'text' },
            { name: 'status', label: 'status', type: 'picker', options: [{ label: 'active', value: 1 }, { label: 'inactive', value: 0 }] },
        ],
        api: {
            list: mainproject_api,
            delete: deletemainproject_api,
            activate: activemainproject_api,
            deactivate: deactivemainproject_api,
            create: creatmainproject_api,
            update: updatemainproject_api,
        },
    },
    unitsubproject: {
        mastertitle: 'subproject',
        addformtitle: 'addsubproject',
        editformtitle: 'editsubproject',
        formRoute: 'unitsubproject',
        displayFields: ['englishname', 'arabicname', 'status'],
        titleField: 'englishname',
        displayLabels: {
            englishname: 'englishname',
            arabicname: 'arabicname',
            status: 'status',
        },
        formFields: [
            { name: 'englishname', label: 'englishname', type: 'text' },
            { name: 'arabicname', label: 'arabicname', type: 'text' },
            { name: 'status', label: 'status', type: 'picker', options: [{ label: 'active', value: 1 }, { label: 'inactive', value: 0 }] },
        ],
        api: {
            list: subproject_api,
            delete: deletesubproject_api,
            activate: activesubproject_api,
            deactivate: deactivesubproject_api,
            create: creatsubproject_api,
            update: updatesubproject_api,
        },
    },   
    landstatus: {
        mastertitle: 'landstatus',
        addformtitle: 'addlandstatus',
        editformtitle: 'editlandstatus',
        formRoute: 'landstatus',
        displayFields: ['englishname', 'arabicname', 'status'],
        titleField: 'englishname',
        displayLabels: {
            englishname: 'englishname',
            arabicname: 'arabicname',
            status: 'status',
        },
        formFields: [
            { name: 'englishname', label: 'englishname', type: 'text' },
            { name: 'arabicname', label: 'arabicname', type: 'text' },
            { name: 'status', label: 'status', type: 'picker', options: [{ label: 'active', value: 1 }, { label: 'inactive', value: 0 }] },
        ],
        api: {
            list: landstatus_api,
            delete: deletelandstatus_api,
            activate: activelandstatus_api,
            deactivate: deactivelandstatus_api,
            create: creatlandstatus_api,
            update: updatelandstatus_api,
        },
    },
    baseevaluation: {
        mastertitle: 'baseevaluation',
        addformtitle: 'addbaseevaluation',
        editformtitle: 'editbaseevaluation',
        formRoute: 'baseevaluation',
        displayFields: ['en_name', 'ar_name', 'status'],
        displayLabels: {
            en_name: 'englishname',
            ar_name: 'arabicname',
            status: 'status',
        },
        titleField: 'en_name',
        formFields: [
            { name: 'en_name', label: 'englishname', type: 'text' },
            { name: 'ar_name', label: 'arabicname', type: 'text' },
            { name: 'status', label: 'status', type: 'picker', options: [{ label: 'active', value: 1 }, { label: 'inactive', value: 0 }] },
        ],
        api: {
            list: buildbase_api,
            delete: deletebuildbase_api,
            activate: activebuildbase_api,
            deactivate: deactivebuildbase_api,
            create: creatbuildbase_api,
            update: updatebuildbase_api,
        },
    },
    systemforms: {
        mastertitle: 'systemforms',
        addformtitle: 'addform',
        editformtitle: 'editform',
        formRoute: 'systemforms',
        displayFields: ['englishname', 'arabicname', 'url', 'status'],
        titleField: 'englishname',
        displayLabels: {
            englishname: 'englishname',
            arabicname: 'arabicname',
            url: 'URL',
            status: 'status',
        },
        formFields: [
            { name: 'englishname' , label: 'englishname', type: 'text' },
            { name: 'arabicname'  , label: 'arabicname', type: 'text' },
            { name: 'status'      , label: 'status', type: 'picker', options: [{ label: 'active', value: 1 }, { label: 'inactive', value: 0 }] },
        ],
        api: {
            list: systemform_api
        },
    },


    pricepolicy: {
        formRoute: 'pricepolicy',
        displayFields: ['englishname', 'arabicname', 'servicefees', 'status'],
        formFields: [
            { name: 'englishname', label: 'englishname', type: 'text' },
            { name: 'arabicname', label: 'arabicname', type: 'text' },
            { name: 'servicefees', label: 'Service Fees', type: 'text' },
            { name: 'status', label: 'status', type: 'picker', options: [{ label: 'active', value: 1 }, { label: 'inactive', value: 0 }] },
        ],
        api: {
            create: '...',
            update: '...',
        },
    },
};
